### ISSUE TITLE
Bug Chainsaw

### ISSUE THREAD

**Issue by Elysian-dev** [minetest-mods/technic#658] opened 2024-12-07 19:22 UTC
**Bug description**

The chainsaw doesn't cut certain trees, or only when they've grown on certain blocks?

I didn't really understand why sometimes I managed to break the apple trees, and sometimes not.

**Comment by SmallJoker** [comment] 2024-12-07 20:26
Duplicate of #619.

This is to prevent cutting down user-build buildings. This safety mechanism depends on trees that are generated with `param0 = 0`. Use the setting `technic_safe_chainsaw = false` to disable it.

**Comment by Elysian-dev** [comment] 2024-12-07 20:29
Sorry.. But thanks !

**Comment by SmallJoker** [comment] 2024-12-07 20:37
I think it might be a good idea to give a feedback to the player as for why it's not cutting everything. Do you think this change would help?
```diff
diff --git a/technic/tools/chainsaw.lua b/technic/tools/chainsaw.lua
index ee8fed7..84afcba 100644
--- a/technic/tools/chainsaw.lua
+++ b/technic/tools/chainsaw.lua
@@ -128,6 +128,7 @@ local function dig_recursive(x, y, z)
        if safe_cut and cutter.param2[i] ~= 0 then
                -- Do not dig manually placed nodes
                -- Problem: moretrees' generated jungle trees use param2 = 2
+               cutter.stopped_by_safe_cut = true
                return
        end
 
@@ -201,6 +202,11 @@ local function chainsaw_dig(player, pos, remaining_charge)
                return
        end
 
+       if cutter.stopped_by_safe_cut then
+               minetest.chat_send_player(player_name, S("The chainsaw could not dig all nodes" ..
+                       " because the safety mechanism was activated."))
+       end
+
        minetest.sound_play("chainsaw", {
                pos = pos,
                gain = 1.0,
```

**Comment by Elysian-dev** [comment] 2024-12-07 20:40
Yes, it could be interesting

**Closed** 2024-12-07 21:17 UTC
Labels: Not a bug
