### ISSUE TITLE
Nuclear fuel lasts too long

### ISSUE THREAD

**Issue by thatgraemeguy** [minetest-mods/technic#234] opened 2015-07-13 11:31 UTC
Nuclear fuel is supposed to last a week according to the manual. I assume this is 1 real-time week, not 1 in-game week. Either way, I have always had nuclear fuel last for a month or more, so something seems to be a bit broken there.

**Comment by est31** [comment] 2015-07-30 23:19
The manual also says that the fuel burning stops if the server unloads the block. Has it been kept loaded all the time?

**Comment by thatgraemeguy** [comment] 2015-07-31 09:35
Probably not. There is still a bug though, as machines run as long as a switching station is loaded, yet nuclear fuel does not deplete under the same circumstances.

I have a switching station at home and quarries attached to the same HV network 2000 nodes away, the quarries will run as long as my switching station at home is loaded, yet the nuclear reactors around 500 nodes away will not deplete their fuel.

**Comment by asl97** [comment] 2015-07-31 10:07
@est31 : if it say that, the manual is outdated, machine is keep running by https://github.com/minetest-technic/technic/commit/563a4c071d5a14905a8ee729705ababf8d46d9f6

@thatgraemeguy : it most likely is depleting but since the depletion is so slow that you don't see it.
you can try adding a `print(burn_time)` at https://github.com/minetest-technic/technic/blob/master/technic/machines/HV/nuclear_reactor.lua#L255

**Comment by thatgraemeguy** [comment] 2015-07-31 11:33
It may be, but there are several players active throughout the day and all of us are typically close to a switching station. Fuel has lasted 2 months already and is still less than 20% depleted.

**Comment by est31** [comment] 2015-07-31 11:45
@asl97 For running the node, it loads the block. The manual is consistent with the actual behaviour here.

**Comment by asl97** [comment] 2015-07-31 11:53
@thatgraemeguy it need to be a switching station on the same network as the reactor for it to run, not just any switching station

**Comment by thatgraemeguy** [comment] 2015-07-31 12:28
@asl97 yes I know, I've built some pretty massive technic infrastructure, I know how it works. The fact is that nuclear fuel lasts too long.

Perhaps the reactor could track the time it was last filled in the metadata and use that instead of just counting when its loaded. Not really sure what's involved in that though.

**Comment by est31** [comment] 2015-07-31 12:45
@asl97 the manual mentions it, although indirectly:
"It is not really intended to be possible to pause a running reactor, but actually disconnecting it from a switching station will have the effect of pausing the week"

**Comment by asl97** [comment] 2015-07-31 13:44
@thatgraemeguy that would make it too short, a week in real time is just too short. not everyone play minetest 24/7 and not every server would always have player let alone in a spot with a switching station connected to the reactor.

@est31 so it doesn't really have anything to do with loaded or not, at least not anymore, it all depend on the switching station, the loading of the block is just a side effect of the power grid checking.

**Comment by thatgraemeguy** [comment] 2015-07-31 14:18
Whether you think it too short or not isn't the issue. The intent of the devs was 1 week, it's documented that way, yet does not work that way, hence its a bug.

The definition of a bug is when software doesn't work in the way it was intended.

**Comment by asl97** [comment] 2015-07-31 14:24
it works as intended, it is documented as 86400 ticks, even if the number is a typo/outdated, it use ticks which means it would only be use when loaded.

**Comment by ShadowNinja** [comment] 2016-03-21 20:44
This is supposed to use game time so that your fuel doesn't disappear if you just stop playing for a few days.  Reducing the amount of game time that the fuel gives you is certainly debatable though.  Just keep in mind, that while one game day may be fine in a singleplayer world, it isn't on a multiplayer server because a reactor near spawn on a popular server will be kept running almost continuously and one game day will be almost equivalent to one real day.

**Comment by HybridDog** [comment] 2017-03-06 19:43
Is the manual fixed yet?

**Comment by VanessaE** [comment] 2017-03-06 21:08
I suppose it's not, yet.

**Comment by cheapie** [comment] 2017-03-11 07:01
This may have been fixed by 088eea1.

**Comment by VanessaE** [comment] 2017-04-14 00:32
Probably fixed by cheapie's commit, and no response from the original author in almost 2 years.  Closing.

**Closed by VanessaE** 2017-04-14 00:32 UTC
Labels: Medium priority
